name: Trigger auto deployment for sailchain

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - '**'
      - '.github/workflows/sailchain-AutoDeployTrigger-fcf874bb-f228-415f-a06a-7c2689257c9e.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SAILCHAIN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SAILCHAIN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SAILCHAIN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile # Assuming your Dockerfile is at the repo root
          registryUrl: sailchain.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }} # Update secret name as needed
          registryPassword: ${{ secrets.ACR_PASSWORD }} # Update secret name as needed
          containerAppName: sailchain
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: sailchain.azurecr.io/sailchain:${{ github.sha }}
